FROM python:2.7.14
# debian 8.9

MAINTAINER aokad <aokad@hgc.jp>

RUN echo "deb http://deb.debian.org/debian stretch main" > /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian stretch-updates main" >> /etc/apt/sources.list && \
    echo "deb http://security.debian.org stretch/updates main" >> /etc/apt/sources.list && \
    apt-get -y update && \
    apt-get install -y dpkg-dev gcc g++ libc6-dev make patch tar unzip && \
    apt-get install -y zlib1g-dev  g++ dh-autoreconf libncurses-dev pkg-config libgd2-xpm-dev && \
    apt-get install -y r-base libcurl4-openssl-dev libdbd-mysql libmysqlclient-dev libgeos-dev libxml2-dev libssl-dev && \
    \
    mkdir -p /tools && \
    \
    cd /tools && \
    wget http://www.cpan.org/src/5.0/perl-5.14.4.tar.gz && \
    tar -xzf perl-5.14.4.tar.gz && \
    rm perl-5.14.4.tar.gz && \
    cd perl-5.14.4 && \
    ./Configure -des -Dprefix=/usr/local/ -Dusethreads && \
    make && \
    make install && \
    \
    cd /tools && \
    wget -nc https://github.com/ICGC-TCGA-PanCancer/PCAP-core/archive/v1.8.1.tar.gz && \
    tar xzvf v1.8.1.tar.gz && \
    rm v1.8.1.tar.gz && \
    cd PCAP-core-1.8.1 && \
    grep -l -r '/usr/bin/perl' * | xargs sed -i.bak -e 's;/usr/bin/perl;/usr/local/bin/perl;g' && \
    cpan -f JSON && \
    bash setup.sh /tools/ICGC

CMD ["/bin/bash"]
