FROM /aokad/genomon2:step1

MAINTAINER aokad <aokad@hgc.jp>

# R package
RUN echo "options(repos='https://cran.rstudio.com/')" > .Rprofile && \
    Rscript -e "install.packages('devtools')" && \
    Rscript -e "install.packages('ggplot2')" && \
    Rscript -e "install.packages('Rcpp')" && \
    Rscript -e "install.packages('rjson')" && \
    Rscript -e "source('http://bioconductor.org/biocLite.R');biocLite(c('GenomicRanges', 'BSgenome.Hsapiens.UCSC.hg19'), ask=FALSE)" && \
    Rscript -e "library(devtools);devtools::install_github('friend1ws/pmsignature')"

CMD ["/bin/bash"]
